// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKFauB5zOifgFANCBvkCyZBejYuXQ-BBY',
    appId: '1:545118974495:web:55559b96d93ea4c08a9b2a',
    messagingSenderId: '545118974495',
    projectId: 'bebecam-9a5fe',
    authDomain: 'bebecam-9a5fe.firebaseapp.com',
    databaseURL: 'https://bebecam-9a5fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bebecam-9a5fe.firebasestorage.app',
    measurementId: 'G-TPVKWF3T2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-m8985FFdBXbNwsQpc3vgHBj2orW2ACM',
    appId: '1:545118974495:android:539420c2e8148aa18a9b2a',
    messagingSenderId: '545118974495',
    projectId: 'bebecam-9a5fe',
    databaseURL: 'https://bebecam-9a5fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bebecam-9a5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOHk1N2gkuck13hX1V8aVgagLzEYKEWhw',
    appId: '1:545118974495:ios:df2ec86554d9796e8a9b2a',
    messagingSenderId: '545118974495',
    projectId: 'bebecam-9a5fe',
    databaseURL: 'https://bebecam-9a5fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bebecam-9a5fe.firebasestorage.app',
    iosBundleId: 'com.erol.bebecam.bebecam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOHk1N2gkuck13hX1V8aVgagLzEYKEWhw',
    appId: '1:545118974495:ios:df2ec86554d9796e8a9b2a',
    messagingSenderId: '545118974495',
    projectId: 'bebecam-9a5fe',
    databaseURL: 'https://bebecam-9a5fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bebecam-9a5fe.firebasestorage.app',
    iosBundleId: 'com.erol.bebecam.bebecam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKFauB5zOifgFANCBvkCyZBejYuXQ-BBY',
    appId: '1:545118974495:web:826a7d48a77d6de88a9b2a',
    messagingSenderId: '545118974495',
    projectId: 'bebecam-9a5fe',
    authDomain: 'bebecam-9a5fe.firebaseapp.com',
    databaseURL: 'https://bebecam-9a5fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bebecam-9a5fe.firebasestorage.app',
    measurementId: 'G-493WHPSTNH',
  );

}